"use client";
import {useEffect,useRef,useState} from "react";
import {drawTruck} from "./yardArt";
import {beatComplete,currentBeat,type Box,type Level,type Target} from "./campaignLevels";

type Props={level:Level;shake:number;autoDrive:boolean;reducedFlash:boolean;onExit:()=>void;onComplete:(score:number,time:number)=>void};
type LiveTarget=Target&{remaining:number;dead:boolean};
type Particle={x:number;y:number;vx:number;vy:number;life:number;color:string;size:number};
type Run={x:number;y:number;heading:number;speed:number;z:number;zv:number;jumpCd:number;nitro:number;powerT:number;powerCooldown:number;stage:number;transition:number;bridge:boolean;score:number;combo:number;comboT:number;time:number;message:string;messageT:number;shake:number;lastSafe:{x:number;y:number;heading:number};targets:LiveTarget[];particles:Particle[];debris:{x:number;y:number;angle:number;size:number}[];finale:number;finished:boolean;bestCombo:number;destroyed:number};
const W=3000,H=2100,clamp=(x:number,a:number,b:number)=>Math.max(a,Math.min(b,x));
const within=(x:number,y:number,r:Box)=>x>r.x&&x<r.x+r.w&&y>r.y&&y<r.y+r.h;
const circleBox=(x:number,y:number,rad:number,r:Box)=>{const px=clamp(x,r.x,r.x+r.w),py=clamp(y,r.y,r.y+r.h);return Math.hypot(x-px,y-py)<rad};
const newRun=(l:Level):Run=>({x:l.start.x,y:l.start.y,heading:l.start.heading,speed:45,z:0,zv:0,jumpCd:0,nitro:100,powerT:0,powerCooldown:0,stage:0,transition:0,bridge:false,score:0,combo:0,comboT:0,time:0,message:l.beats[0].radio,messageT:5,shake:0,lastSafe:{...l.start},targets:l.targets.map(t=>({...t,remaining:t.hp,dead:false})),particles:[],debris:[],finale:0,finished:false,bestCombo:0,destroyed:0});
const hash=(n:number)=>{const v=Math.sin(n*127.13+78.21)*43758.5;return v-Math.floor(v)};
function scene(level:Level){const cv=document.createElement("canvas");cv.width=W;cv.height=H;const c=cv.getContext("2d")!,[ground,road,accent]=level.palette;
 c.fillStyle=ground;c.fillRect(0,0,W,H);
 for(let i=0;i<2600;i++){const x=hash(i*3)*W,y=hash(i*3+1)*H,r=1+hash(i*3+2)*12;c.fillStyle=i%4?"#08151a24":"#dbbd8b29";c.fillRect(x,y,r,r*.45)}
 for(const r of level.roads){c.fillStyle="#14202766";c.fillRect(r.x+12,r.y+13,r.w,r.h);c.fillStyle=road;c.fillRect(r.x,r.y,r.w,r.h);c.strokeStyle="#d7c5a849";c.lineWidth=4;c.strokeRect(r.x+5,r.y+5,r.w-10,r.h-10);c.strokeStyle="#e3d5aa55";c.lineWidth=5;c.setLineDash([36,42]);c.beginPath();if(r.w>r.h){c.moveTo(r.x+20,r.y+r.h/2);c.lineTo(r.x+r.w-20,r.y+r.h/2)}else{c.moveTo(r.x+r.w/2,r.y+20);c.lineTo(r.x+r.w/2,r.y+r.h-20)}c.stroke();c.setLineDash([])}
 level.walls.forEach((r,i)=>{c.fillStyle="#07111680";c.fillRect(r.x+21,r.y+22,r.w,r.h);c.fillStyle=level.terrain==="county"?i%2?"#87765f":"#6c755e":level.terrain==="glass"?"#4d7582":level.terrain==="timber"?"#806b50":"#697275";c.fillRect(r.x,r.y,r.w,r.h);c.strokeStyle="#1b2d34";c.lineWidth=9;c.strokeRect(r.x+3,r.y+3,r.w-6,r.h-6);c.strokeStyle="#dde3cf44";c.lineWidth=4;for(let x=r.x+34;x<r.x+r.w-15;x+=58){c.beginPath();c.moveTo(x,r.y+14);c.lineTo(x,r.y+r.h-14);c.stroke()}c.fillStyle="#14242a99";c.fillRect(r.x+r.w*.17,r.y+r.h*.21,r.w*.28,r.h*.14);c.fillRect(r.x+r.w*.6,r.y+r.h*.55,r.w*.19,r.h*.15)});
 if(level.terrain==="rail"){for(let y of [730,1330]){c.fillStyle="#18272a";c.fillRect(300,y,2400,45);for(let x=330;x<2700;x+=55){c.fillStyle="#9b8765";c.fillRect(x,y-8,12,61)}c.fillStyle="#a6afb0";c.fillRect(300,y+18,2400,5)}}
 if(level.terrain==="stadium"){for(let r=690;r>=440;r-=70){c.strokeStyle=r%140?"#9b8f78":"#394b51";c.lineWidth=48;c.beginPath();c.ellipse(1440,1050,r,r*.67,0,0,Math.PI*2);c.stroke()}c.fillStyle="#52685b";c.beginPath();c.ellipse(1440,1050,355,235,0,0,Math.PI*2);c.fill();for(let i=0;i<24;i++){const a=i*Math.PI/12;c.strokeStyle="#1b292b88";c.lineWidth=5;c.beginPath();c.moveTo(1440+390*Math.cos(a),1050+275*Math.sin(a));c.lineTo(1440+720*Math.cos(a),1050+480*Math.sin(a));c.stroke()}}
 if(level.terrain==="dam"){const water=c.createLinearGradient(2750,0,3000,0);water.addColorStop(0,"#113f50");water.addColorStop(1,"#2b6980");c.fillStyle=water;c.fillRect(2750,0,250,H);for(let y=40;y<H;y+=70){c.strokeStyle="#bedbdf66";c.lineWidth=5;c.beginPath();c.moveTo(2770,y);c.lineTo(2920,y-10);c.lineTo(2990,y+5);c.stroke()}for(let x=1420;x<2850;x+=120){c.fillStyle="#a5a69b";c.fillRect(x,170,24,265);c.fillStyle="#243e47";c.fillRect(x+24,210,47,50)}}
 if(level.terrain==="freight"){for(let y of [320,720,1230,1820])for(let x=900;x<2200;x+=210){c.fillStyle=x%3?"#a57551":"#58777d";c.fillRect(x,y,150,65);c.strokeStyle="#15262b";c.lineWidth=4;c.strokeRect(x,y,150,65)}}
 if(level.terrain==="timber"){for(let i=0;i<28;i++){const x=280+hash(i)*1950,y=i%2?300:1850;c.fillStyle=i%2?"#76563b":"#93724b";c.fillRect(x,y,120,18);c.fillStyle="#c7a77c";c.beginPath();c.arc(x+10,y+9,8,0,7);c.fill()}}
 if(level.hazard){const r=level.hazard;c.fillStyle=level.terrain==="dam"?"#0d4358":"#132e39";c.fillRect(r.x,r.y,r.w,r.h);for(let y=r.y+30;y<r.y+r.h;y+=68){c.strokeStyle="#5f9ba075";c.lineWidth=5;c.beginPath();c.moveTo(r.x+10,y);c.lineTo(r.x+r.w*.55,y-14);c.lineTo(r.x+r.w-15,y+4);c.stroke()}}
 c.fillStyle=accent+"88";c.font="800 24px system-ui";c.letterSpacing="3px";c.fillText(level.region+" / "+level.name.toUpperCase(),130,2050);
 c.fillStyle="#f5d48e";c.beginPath();c.arc(level.exit.x,level.exit.y,45,0,Math.PI*2);c.strokeStyle=accent;c.lineWidth=8;c.stroke();c.fillStyle="#142229";c.font="800 24px system-ui";c.fillText("EXTRACTION",level.exit.x-76,level.exit.y-62);return cv}
function targetArt(c:CanvasRenderingContext2D,o:LiveTarget,active:boolean,time:number,accent:string){c.save();c.translate(o.x,o.y);c.globalAlpha=o.dead?.33:1;c.fillStyle="#071418a3";c.fillRect(-o.w/2+10,-o.h/2+12,o.w,o.h);c.fillStyle=o.kind==="light"?"#a3784f":o.kind==="gate"?"#957c56":o.kind==="node"?"#678894":"#7b8a88";c.fillRect(-o.w/2,-o.h/2,o.w,o.h);c.strokeStyle="#1b282d";c.lineWidth=5;c.strokeRect(-o.w/2,-o.h/2,o.w,o.h);
 if(o.kind==="support"){c.fillStyle="#303e42";c.fillRect(-o.w*.22,-o.h*.48,o.w*.44,o.h*.96);for(let y=-25;y<28;y+=17){c.fillStyle="#d5b76e";c.fillRect(-o.w*.45,y,14,8)}}else if(o.kind==="gate"){for(let y=-o.h/2+12;y<o.h/2;y+=29){c.strokeStyle="#263337";c.lineWidth=10;c.beginPath();c.moveTo(-o.w/2+5,y);c.lineTo(o.w/2-5,y+17);c.stroke()}}else if(o.kind==="node"){c.fillStyle="#162c35";c.beginPath();c.arc(0,0,30,0,7);c.fill();c.fillStyle="#b9dde0";c.beginPath();c.arc(0,0,13,0,7);c.fill()}else{c.strokeStyle="#24363a";c.lineWidth=3;for(let x=-o.w/2+14;x<o.w/2;x+=22){c.beginPath();c.moveTo(x,-o.h/2+7);c.lineTo(x,o.h/2-7);c.stroke()}}
 if(!o.dead&&active){c.strokeStyle=accent;c.lineWidth=6;c.strokeRect(-o.w/2-8,-o.h/2-8,o.w+16,o.h+16);c.fillStyle="#ffefbd";c.beginPath();c.arc(0,-o.h/2-22+Math.sin(time*4)*5,7,0,7);c.fill();c.font="800 19px system-ui";c.textAlign="center";c.fillText(o.label,0,-o.h/2-48)}
 c.restore()}
function landmarkArt(c:CanvasRenderingContext2D,l:Level,s:Run){const down=s.stage>=2,t=s.transition;c.save();c.lineCap="round";
 if(l.terrain==="county"&&l.id===2){c.translate(2150,1060);c.rotate(down?-.64*t-.64*(1-t):0);c.fillStyle="#b6b8a6";c.fillRect(-32,-350,64,360);c.fillStyle="#5e8990";c.beginPath();c.ellipse(0,-340,155,85,0,0,7);c.fill();c.fillStyle="#d3d0b1";c.fillRect(-115,-395,230,30);c.strokeStyle="#2a4147";c.lineWidth=12;for(let x=-110;x<=110;x+=55){c.beginPath();c.moveTo(x,-390);c.lineTo(x,-290);c.stroke()}}
 if(l.terrain==="mall"){c.fillStyle=down?"#597b8299":"#add8d888";c.beginPath();c.ellipse(1750,1050,440,230,0,0,7);c.fill();c.strokeStyle="#233f46";c.lineWidth=14;for(let x=1370;x<2170;x+=90){c.beginPath();c.moveTo(x,850);c.lineTo(x+100,1270);c.stroke()}if(down){c.fillStyle="#273d42bb";c.fillRect(1660,950,260,220)}}
 if(l.terrain==="concrete"){for(let i=0;i<3;i++){c.fillStyle=i%2?"#adb5ae99":"#818f9399";c.save();c.translate(1100+i*470,1240-i*270);c.rotate(down?(.08+i*.08)*t:.0);c.fillRect(-250,-60,500,105);c.restore()}}
 if(l.terrain==="metro"){c.fillStyle=down?"#798b8baa":"#798b8b66";c.save();c.translate(2180,1040);c.rotate(down?-.13*t:0);c.fillRect(-340,-95,650,120);c.strokeStyle="#d8bd87";c.lineWidth=10;c.strokeRect(-340,-95,650,120);c.restore()}
 if(l.terrain==="glass"){for(let i=0;i<2;i++){c.save();c.translate(1480+i*490,940+i*220);c.rotate(down?(i?-.3:.3)*t:0);c.fillStyle="#8bc6d177";c.fillRect(-90,-230,180,340);c.strokeStyle="#c6e3df";c.lineWidth=8;for(let j=-60;j<75;j+=35){c.beginPath();c.moveTo(j,-220);c.lineTo(j,100);c.stroke()}c.restore()}}
 if(l.terrain==="rail"){c.strokeStyle=down?"#718e91":"#bec6b3";c.lineWidth=30;c.beginPath();c.moveTo(1080,690);c.lineTo(2260,690+(down?210*t:0));c.stroke();for(let x=1110;x<2230;x+=80){c.fillStyle="#3e5a60";c.fillRect(x,690+(down?140*t:0),35,160)}}
 if(l.terrain==="vertical"){c.save();c.translate(2050,760);c.rotate(s.stage>=3?-.26*t:s.stage>=2?-.1*t:0);for(let i=0;i<5;i++){c.fillStyle=i%2?"#7290a2aa":"#bac6c2aa";c.fillRect(-160+i*10,-420+i*85,320-i*20,75);c.strokeStyle="#253b49";c.lineWidth=8;c.strokeRect(-160+i*10,-420+i*85,320-i*20,75)}c.restore()}
 if(l.terrain==="dam"){const cracked=s.targets.filter(o=>o.id.startsWith("node-")&&o.dead).length;c.fillStyle="#a9b9ae99";c.fillRect(2570,210,135,1740);c.strokeStyle="#263d46";c.lineWidth=15;c.strokeRect(2570,210,135,1740);for(let i=0;i<cracked;i++){c.strokeStyle="#102c3b";c.lineWidth=14;c.beginPath();c.moveTo(2640,390+i*490);c.lineTo(2590,590+i*490);c.lineTo(2680,730+i*490);c.stroke();c.strokeStyle="#8bd5e3a6";c.lineWidth=5;c.stroke()}if(s.finale>0){const breach=Math.min(1,s.finale/5);c.fillStyle="#183f4f";c.fillRect(2560,470,155*breach,450*breach);c.fillStyle="#a8e5e9b9";for(let i=0;i<14;i++){let y=490+i*35;c.fillRect(2580+Math.sin(s.time*3+i)*30,y,breach*(150+i*28),12+breach*22)}}}
 c.restore()}
function mini(c:CanvasRenderingContext2D,s:Run,l:Level){const x=1208,y=685,w=210,h=178;c.fillStyle="#071014e5";c.fillRect(x,y,w,h);c.strokeStyle="#a2aeaa";c.lineWidth=2;c.strokeRect(x,y,w,h);c.fillStyle="#68797b";for(const r of l.roads)c.fillRect(x+r.x/W*w,y+r.y/H*h,Math.max(2,r.w/W*w),Math.max(2,r.h/H*h));if(l.hazard){c.fillStyle="#2a7592";c.fillRect(x+l.hazard.x/W*w,y+l.hazard.y/H*h,l.hazard.w/W*w,l.hazard.h/H*h)}if(s.bridge&&l.bridge){c.fillStyle="#e0bb6e";c.fillRect(x+l.bridge.x/W*w,y+l.bridge.y/H*h,l.bridge.w/W*w,l.bridge.h/H*h)}for(const o of s.targets)if(o.stage===s.stage&&!o.dead){c.fillStyle="#f1bd67";c.fillRect(x+o.x/W*w-3,y+o.y/H*h-3,6,6)}c.fillStyle="#f35636";c.beginPath();c.arc(x+s.x/W*w,y+s.y/H*h,5,0,7);c.fill()}
export default function CampaignDistrict({level,shake,autoDrive,reducedFlash,onExit,onComplete}:Props){const canvasRef=useRef<HTMLCanvasElement>(null),stateRef=useRef<Run>(newRun(level)),keys=useRef<Record<string,boolean>>({});const [caption,setCaption]=useState(level.beats[0].title);
 useEffect(()=>{stateRef.current=newRun(level);setCaption(level.beats[0].title)},[level]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{keys.current[e.code]=true;if(["Space","ArrowUp","ArrowDown","ArrowLeft","ArrowRight"].includes(e.code))e.preventDefault();if(e.code==="Escape")onExit()};const up=(e:KeyboardEvent)=>{keys.current[e.code]=false};addEventListener("keydown",down);addEventListener("keyup",up);return()=>{removeEventListener("keydown",down);removeEventListener("keyup",up)}},[onExit]);
 useEffect(()=>{const canvas=canvasRef.current!,c=canvas.getContext("2d")!,backdrop=scene(level);let raf=0,last=performance.now(),acc=0;
 const say=(s:Run,msg:string,sec=3)=>{s.message=msg;s.messageT=sec};
 const burst=(s:Run,x:number,y:number,color:string,n=25)=>{for(let i=0;i<n;i++){const a=Math.random()*7,m=80+Math.random()*260;s.particles.push({x,y,vx:Math.cos(a)*m,vy:Math.sin(a)*m,life:.5+Math.random(),color,size:4+Math.random()*13})}};
 const recover=(s:Run)=>{s.x=s.lastSafe.x;s.y=s.lastSafe.y;s.heading=s.lastSafe.heading;s.speed=0;s.z=0;s.zv=0;s.combo=0;s.shake=.3;say(s,"TOW RECOVERY // REJOIN THE ROUTE",2)};
 const strike=(s:Run,o:LiveTarget,boost:boolean)=>{if(o.dead)return;if(o.stage!==s.stage){s.speed*=-.2;say(s,"MARKED OBJECTIVE IS ELSEWHERE",1.4);return}const beat=level.beats[s.stage];const order=beat.targets.filter(id=>!s.targets.find(t=>t.id===id)?.dead);if(level.id===18&&s.stage===2&&order[0]!==o.id){s.speed*=-.2;say(s,`BREACH SEQUENCE // ${order[0]?.toUpperCase()} FIRST`,2);return}
 if(o.verb==="west"&&s.x>o.x-18){s.speed*=-.25;say(s,"STRIKE THE EXPOSED WEST FACE",1.8);return}
 if(o.verb==="jump"&&s.z<25){s.speed*=-.25;say(s,"HYDRAULIC JUMP REQUIRED",1.8);return}
 if(o.verb==="nitro"&&!boost&&s.powerT<=0){s.speed*=-.25;say(s,"REINFORCED // NITRO IMPACT",1.8);return}
 if(level.id===18&&o.id==="central-breach"&&s.powerT<=0){s.speed*=-.25;say(s,"TAKE THE OVERDRIVE CHARGE BEFORE THE FINAL LAUNCH",2);return}
 if(o.verb==="vector"&&s.powerT<=0){s.speed*=-.25;say(s,"COLLECT VECTOR SHEAR IN THE SOUTH PLAZA",2);return}
 if(Math.abs(s.speed)<(o.kind==="light"?55:80)){s.speed*=-.3;say(s,"BUILD IMPACT SPEED",1.4);return}
 o.remaining-=boost||s.powerT>0||level.classRank>=5?2:1;s.speed*=.52;s.shake=reducedFlash?.15:.4;burst(s,o.x,o.y,o.kind==="node"?"#8ad5e6":"#d6b176",o.remaining<=0?38:14);
 if(o.remaining<=0){o.dead=true;s.destroyed++;s.combo++;s.bestCombo=Math.max(s.bestCombo,s.combo);s.comboT=2.8;s.score+=Math.round((o.kind==="node"?2400:o.kind==="support"?1500:600)*(1+s.combo*.28));s.nitro=clamp(s.nitro+17,0,100);for(let i=0;i<7;i++)s.debris.push({x:o.x+(Math.random()-.5)*80,y:o.y+(Math.random()-.5)*80,angle:Math.random()*7,size:13+Math.random()*21});say(s,`${o.label} // DOWN`,1.6);
 const dead=new Set(s.targets.filter(t=>t.dead).map(t=>t.id));if(beatComplete(level,s.stage,dead)){if(beat.event){s.transition=.001;say(s,beat.radio,4);burst(s,level.id===18?2400:2100,1050,"#d7bb83",70)}s.stage++;if(s.stage<level.beats.length){setCaption(level.beats[s.stage].title);if(!beat.event)say(s,level.beats[s.stage].radio,4)}else if(level.id===18){s.finale=.001;say(s,"CONTROLLED BREACH // NO RETURN",5)}else{setCaption("REACH EXTRACTION");say(s,"ROUTE OPEN // DRIVE TO EXTRACTION",4)}}}
 };
 const step=(dt:number)=>{const s=stateRef.current;if(s.finished)return;s.time+=dt;s.messageT-=dt;s.shake=Math.max(0,s.shake-dt);s.comboT-=dt;if(s.comboT<=0)s.combo=0;s.powerT=Math.max(0,s.powerT-dt);s.powerCooldown=Math.max(0,s.powerCooldown-dt);
 for(const p of s.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.97;p.vy*=.97;p.life-=dt}s.particles=s.particles.filter(p=>p.life>0).slice(-280);
 if(s.transition>0){s.transition=Math.min(1,s.transition+dt/3.4);s.shake=Math.max(s.shake,.3);if(s.transition===1){if(level.bridge)s.bridge=true;s.transition=0;say(s,level.id===18?"FRACTURE SPREADING // WATER RISING":"LANDMARK DOWN // ROUTE TRANSFORMED",4)}}
 if(s.finale>0){s.finale+=dt;s.shake=.55;if(s.finale>7){s.finished=true;onComplete(s.score+9000,s.time)}return}
 const k=keys.current,g=navigator.getGamepads?.()[0];let steer=(k.KeyD||k.ArrowRight?1:0)-(k.KeyA||k.ArrowLeft?1:0),throttle=(k.KeyW||k.ArrowUp?1:0)-(k.KeyS||k.ArrowDown?1:0),boost=!!(k.ShiftLeft||k.ShiftRight),jump=!!k.Space;
 if(g){if(Math.abs(g.axes[0])>.16)steer=g.axes[0];if(Math.abs(g.axes[1])>.16)throttle=-g.axes[1];boost=boost||!!g.buttons[0]?.pressed;jump=jump||!!g.buttons[1]?.pressed}if((autoDrive||navigator.maxTouchPoints>0)&&throttle===0)throttle=1;
 const onRoad=level.roads.some(r=>within(s.x,s.y,r)),usingBoost=boost&&s.nitro>0,max=(usingBoost?480:310)*(onRoad?1:.73)*(1+level.classRank*.025);s.speed+=throttle*(usingBoost?340:200)*dt;s.speed*=Math.pow(throttle===0?.98:.996,dt*60);s.speed=clamp(s.speed,-110,max);s.heading+=steer*1.95/(1+Math.abs(s.speed)/390)*dt*(s.speed<0?-1:1);if(usingBoost)s.nitro=Math.max(0,s.nitro-24*dt);else s.nitro=Math.min(100,s.nitro+2.2*dt);
 if(jump&&s.jumpCd<=0&&s.z===0){s.zv=250;s.jumpCd=.75}if(s.jumpCd>0)s.jumpCd-=dt;s.zv-=530*dt;s.z=Math.max(0,s.z+s.zv*dt);if(s.z===0)s.zv=0;
 const ox=s.x,oy=s.y;s.x=clamp(s.x+Math.cos(s.heading)*s.speed*dt,45,W-45);s.y=clamp(s.y+Math.sin(s.heading)*s.speed*dt,45,H-45);
 for(const wall of level.walls)if(circleBox(s.x,s.y,37,wall)){s.x=ox;s.y=oy;s.speed*=-.19;s.shake=.14;break}
 if(level.hazard&&within(s.x,s.y,level.hazard)&&!(s.bridge&&level.bridge&&within(s.x,s.y,level.bridge))&&s.z<45)recover(s);
 if(onRoad&&Math.abs(s.speed)<290)s.lastSafe={x:s.x,y:s.y,heading:s.heading};
 if(Math.hypot(s.x-level.power.x,s.y-level.power.y)<78&&s.powerCooldown===0){s.powerCooldown=level.power.type==="vector"?12:18;s.powerT=level.power.type==="vector"?26:level.power.type==="overdrive"?18:10;s.nitro=100;s.score+=300;say(s,level.power.type==="vector"?"VECTOR SHEAR CHARGED":level.power.type==="overdrive"?"OVERDRIVE CHARGED":"NITRO REFILLED",2)}
 for(const o of s.targets)if(!o.dead&&circleBox(s.x,s.y,s.z>30?23:39,{x:o.x-o.w/2,y:o.y-o.h/2,w:o.w,h:o.h})){strike(s,o,usingBoost);break}
 if(s.stage>=level.beats.length&&Math.hypot(s.x-level.exit.x,s.y-level.exit.y)<100){s.finished=true;onComplete(s.score+Math.max(0,7000-s.time*9),s.time)}
 };
 const draw=()=>{const s=stateRef.current,scale=.73,camX=clamp(s.x+Math.cos(s.heading)*140,1440/(2*scale),W-1440/(2*scale)),camY=clamp(s.y+Math.sin(s.heading)*110,900/(2*scale),H-900/(2*scale));c.setTransform(1,0,0,1,0,0);c.fillStyle="#101a1f";c.fillRect(0,0,1440,900);c.save();c.translate(720+(Math.random()-.5)*s.shake*shake*14,450+(Math.random()-.5)*s.shake*shake*14);c.scale(scale,scale);c.translate(-camX,-camY);c.drawImage(backdrop,0,0);
 landmarkArt(c,level,s);
 if(level.bridge&&(s.bridge||s.transition>0)&&level.bridge){const r=level.bridge;c.save();c.globalAlpha=s.bridge?1:s.transition;c.fillStyle="#667776";c.fillRect(r.x,r.y,r.w,r.h);c.strokeStyle="#ddaf64";c.lineWidth=16;c.strokeRect(r.x+8,r.y+7,r.w-16,r.h-14);for(let x=r.x+16;x<r.x+r.w;x+=32){c.fillStyle="#293a3e";c.fillRect(x,r.y+15,9,r.h-30)}c.restore()}
 if(level.terrain==="dam"){for(let i=0;i<Math.max(0,s.stage-2);i++){c.strokeStyle="#101b20";c.lineWidth=14;c.beginPath();c.moveTo(1800+i*220,320);c.lineTo(1920+i*210,650);c.lineTo(2020+i*230,950);c.stroke();c.strokeStyle="#c9e9e880";c.lineWidth=6;c.stroke()}if(s.finale>0){c.fillStyle=`rgba(120,206,226,${Math.min(.75,s.finale/8)})`;c.fillRect(1900,400,1200,1500)}}
 for(const d of s.debris){c.save();c.translate(d.x,d.y);c.rotate(d.angle);c.fillStyle="#8b8f82";c.fillRect(-d.size/2,-d.size/2,d.size,d.size*.6);c.restore()}
 for(const o of s.targets)targetArt(c,o,o.stage===s.stage&&!o.dead,s.time,level.palette[2]);
 if(s.powerCooldown<1){c.fillStyle=level.power.type==="vector"?"#7ed6ef":"#f9ab57";c.shadowColor=c.fillStyle;c.shadowBlur=25;c.beginPath();c.arc(level.power.x,level.power.y,35,0,7);c.fill();c.shadowBlur=0;c.fillStyle="#1b3036";c.font="900 29px system-ui";c.textAlign="center";c.fillText(level.power.type==="vector"?"V":level.power.type==="overdrive"?"O":"N",level.power.x,level.power.y+11);c.textAlign="left"}
 for(const p of s.particles){c.globalAlpha=Math.max(0,p.life);c.fillStyle=p.color;c.fillRect(p.x,p.y,p.size,p.size)}c.globalAlpha=1;drawTruck(c,s.x,s.y,s.z,s.heading,keys.current.ShiftLeft||s.powerT>0,s.time);c.restore();
 c.setTransform(1,0,0,1,0,0);c.fillStyle="#071014e8";c.fillRect(24,22,680,135);c.strokeStyle=level.palette[2];c.lineWidth=3;c.strokeRect(24,22,680,135);c.fillStyle=level.palette[2];c.font="800 16px system-ui";c.fillText(`${level.region} // ${level.name.toUpperCase()} // CLASS ${level.classRank}`,43,49);c.fillStyle="#f5f2eb";c.font="800 21px system-ui";c.fillText(caption,43,86);const beat=level.beats[s.stage];c.fillStyle="#adbdc1";c.font="15px system-ui";c.fillText(beat?`${beat.targets.filter(id=>s.targets.find(t=>t.id===id)?.dead).length} / ${beat.quota??beat.targets.length} TARGETS   ·   ${level.objective}`:"EXTRACTION OPEN // FOLLOW THE MARKER",43,123);
 c.fillStyle="#071014e8";c.fillRect(1100,22,316,130);c.fillStyle="#fff";c.font="800 20px system-ui";c.fillText(`${Math.round(s.score).toLocaleString()}  /  x${Math.max(1,s.combo)}`,1120,54);c.fillStyle="#34444a";c.fillRect(1120,75,270,17);c.fillStyle=level.palette[2];c.fillRect(1120,75,s.nitro/100*270,17);c.fillStyle="#b7c1c3";c.font="14px system-ui";c.fillText(`NITRO ${Math.round(s.nitro)}%   ·   ${Math.floor(s.time/60).toString().padStart(2,"0")}:${Math.floor(s.time%60).toString().padStart(2,"0")}`,1120,124);mini(c,s,level);
 if(s.messageT>0){c.fillStyle="#071014e6";c.fillRect(325,807,790,54);c.strokeStyle=level.palette[2];c.strokeRect(325,807,790,54);c.fillStyle="#fff";c.textAlign="center";c.font="800 19px system-ui";c.fillText(s.message,720,841);c.textAlign="left"}
 if(s.finale>0){c.fillStyle=`rgba(13,35,47,${Math.min(.75,s.finale/10)})`;c.fillRect(0,0,1440,900);c.fillStyle="#fff";c.font="900 52px system-ui";c.textAlign="center";c.fillText(s.finale<3?"THE DAM IS GIVING WAY":s.finale<5?"THE LINE IS ACROSS":"NO RETURN",720,420);c.textAlign="left"}
 };
 const loop=(now:number)=>{acc+=Math.min(.05,(now-last)/1000);last=now;while(acc>=1/60){step(1/60);acc-=1/60}draw();raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)
 },[level,shake,autoDrive,reducedFlash,onComplete,caption]);
 const touch=(code:string,on:boolean)=>{keys.current[code]=on};return <section className="game-wrap"><canvas ref={canvasRef} width={1440} height={900} aria-label={`Playing ${level.name}`}/><button className="pause" onClick={onExit} aria-label="Pause">Ⅱ</button><div className="touch"><button onPointerDown={()=>touch("KeyA",true)} onPointerUp={()=>touch("KeyA",false)} onPointerCancel={()=>touch("KeyA",false)}>◀</button><button onPointerDown={()=>touch("KeyD",true)} onPointerUp={()=>touch("KeyD",false)} onPointerCancel={()=>touch("KeyD",false)}>▶</button><button className="brake" onPointerDown={()=>touch("KeyS",true)} onPointerUp={()=>touch("KeyS",false)} onPointerCancel={()=>touch("KeyS",false)}>BRAKE</button><button className="jump" onPointerDown={()=>touch("Space",true)} onPointerUp={()=>touch("Space",false)} onPointerCancel={()=>touch("Space",false)}>JUMP</button><button className="nitro" onPointerDown={()=>touch("ShiftLeft",true)} onPointerUp={()=>touch("ShiftLeft",false)} onPointerCancel={()=>touch("ShiftLeft",false)}>NITRO</button></div></section>
}
