"use client";
import {useCallback,useEffect,useState} from "react";
import Image from "next/image";
import GoldDistrict from "./GoldDistrict";
import CampaignDistrict from "./CampaignDistrict";
import {CAMPAIGN,LEVEL_IDS,type Level} from "./campaignLevels";

type Screen="menu"|"map"|"game"|"results"|"contracts"|"garage"|"settings"|"credits";
type SaveData={unlocked:number;completed:number[];medals:Record<number,number>;best:Record<number,number>;score:number;reducedFlash:boolean;shake:number;autoDrive:boolean;sound:boolean};
type Result={score:number;time:number;medals:number;id:number};
const REGIONS=[
 ["RUST COUNTY","YARDBREAKER"],["COMMERCE BELT","ROADHAMMER"],["METRO FRINGE","BLOCKBUSTER"],
 ["CIVIC WORKS","COLOSSUS"],["VERTICAL CITY","TOWERKILLER"],["WATERWORKS","DAM-BREAKER"],
] as const;
const empty:SaveData={unlocked:1,completed:[],medals:{},best:{},score:0,reducedFlash:false,shake:.65,autoDrive:false,sound:true};
const saveKey="iron-outlaw-save-v2";
function loadSave():SaveData{try{const value=JSON.parse(localStorage.getItem(saveKey)||"{}"),completed:number[]=Array.isArray(value.completed)?value.completed.filter((id:number)=>LEVEL_IDS.includes(id)):[];return{...empty,...value,unlocked:Math.max(completed.includes(1)?2:1,Math.min(CAMPAIGN.length,value.unlocked||1)),completed}}catch{return empty}}
function fmt(n:number){return `${String(Math.floor(n/60)).padStart(2,"0")}:${String(Math.floor(n%60)).padStart(2,"0")}`}
export default function IronOutlawGame(){const [screen,setScreen]=useState<Screen>("menu"),[save,setSave]=useState<SaveData>(empty),[selected,setSelected]=useState(0),[result,setResult]=useState<Result>({score:0,time:0,medals:0,id:1}),[muted,setMuted]=useState(false);
 useEffect(()=>{const id=requestAnimationFrame(()=>setSave(loadSave()));return()=>cancelAnimationFrame(id)},[]);
 const persist=useCallback((next:SaveData)=>{setSave(next);localStorage.setItem(saveKey,JSON.stringify(next))},[]);
 const start=useCallback((index:number)=>{if(index<0||index>=CAMPAIGN.length||index+1>save.unlocked)return;setSelected(index);setScreen("game")},[save.unlocked]);
 const continueGame=()=>start(Math.min(save.unlocked-1,CAMPAIGN.length-1));
 const finish=useCallback((score:number,time:number)=>{const level=CAMPAIGN[selected],medals=1+(time<(level.parSeconds??300)?1:0)+(score>15000+level.classRank*3500?1:0),next:SaveData={...save,unlocked:Math.max(save.unlocked,Math.min(CAMPAIGN.length,selected+2)),completed:[...new Set([...save.completed,level.id])],medals:{...save.medals,[level.id]:Math.max(save.medals[level.id]||0,medals)},best:{...save.best,[level.id]:Math.max(save.best[level.id]||0,Math.round(score))},score:Math.max(save.score,Math.round(score))};persist(next);setResult({score:Math.round(score),time,medals,id:level.id});setTimeout(()=>setScreen("results"),level.id===18?500:700)},[selected,save,persist]);
 const level=CAMPAIGN[selected];return <main className={`shell ${screen==="game"?"in-game":""}`}>
 {screen==="menu"&&<Menu save={save} onContinue={continueGame} onNav={setScreen}/>}
 {screen==="map"&&<CampaignMap save={save} selected={selected} setSelected={setSelected} start={start} back={()=>setScreen("menu")}/>}
 {screen==="game"&&(level.id===1?<GoldDistrict key="gold" shake={save.shake} autoDrive={save.autoDrive} reducedFlash={save.reducedFlash} onExit={()=>setScreen("map")} onComplete={finish}/>:<CampaignDistrict key={level.id} level={level} shake={save.shake} autoDrive={save.autoDrive} reducedFlash={save.reducedFlash} onExit={()=>setScreen("map")} onComplete={finish}/>)}
 {screen==="results"&&<Results result={result} level={level} next={()=>start(Math.min(selected+1,CAMPAIGN.length-1))} map={()=>setScreen("map")} credits={()=>setScreen("credits")}/>}
 {screen==="contracts"&&<Replays save={save} start={start} back={()=>setScreen("menu")}/>}
 {screen==="garage"&&<Garage save={save} back={()=>setScreen("menu")}/>}
 {screen==="settings"&&<Settings save={save} persist={persist} muted={muted} setMuted={setMuted} back={()=>setScreen("menu")}/>}
 {screen==="credits"&&<Credits completed={save.completed.includes(18)} back={()=>setScreen("menu")}/>}
 </main>}
function Brand(){return <div className="brand"><div className="iron">IRON</div><div className="outlaw">OUTLAW</div><div className="wing">☠</div></div>}
function Menu({save,onContinue,onNav}:{save:SaveData;onContinue:()=>void;onNav:(s:Screen)=>void}){const next=CAMPAIGN[Math.min(save.unlocked-1,CAMPAIGN.length-1)];return <section className="menu-screen"><div className="menu-shade"/><div className="menu-left"><Brand/><div className="kicker">EVACUATION ROUTE COMMAND // TWELVE DISTRICT CAMPAIGN</div><div className="menu-list"><button className="menu-entry active" onClick={onContinue}><span className="big-icon">▶</span><span><b>{save.completed.includes(18)?"REPLAY MEGA DAM":`DEPLOY TO ${next.name.toUpperCase()}`}</b><small>{save.completed.length} of {CAMPAIGN.length} districts cleared</small></span></button>{[["CAMPAIGN MAP","Choose an unlocked district","map"],["REPLAYS","Chase better times and medals","contracts"],["GARAGE","Six evolving demolition chassis","garage"],["SETTINGS","Controls & accessibility","settings"],["CREDITS","The evacuation line","credits"]].map(([a,b,s],i)=><button className="menu-entry" onClick={()=>onNav(s as Screen)} key={a}><span className="big-icon">{["▣","↺","⚙","☷","★"][i]}</span><span><b>{a}</b><small>{b}</small></span></button>)}</div></div><div className="profile"><b>OUTLAW</b><span>CLASS {Math.max(1,CAMPAIGN[Math.min(save.unlocked-1,CAMPAIGN.length-1)].classRank)} // EVACUATION CREW</span><strong>$ {Math.round(save.score).toLocaleString()}</strong></div><div className="broadcast"><b>OUTLAW BROADCAST</b><div className="wave">▂▅▃▆▂▇▅▂▆▃▆▂▇▃▆</div><p>{save.completed.includes(18)?"The line crossed safely. Far downstream, an engine turns over.":`${next.region}: ${next.objective}`}</p></div></section>}
function CampaignMap({save,selected,setSelected,start,back}:{save:SaveData;selected:number;setSelected:(n:number)=>void;start:(n:number)=>void;back:()=>void}){const d=CAMPAIGN[selected],locked=selected+1>save.unlocked;return <section className="panel-screen map-screen"><Top title="CAMPAIGN ROUTE // THE FLOOD IS COMING" back={back}/><div className="flood-line" style={{width:`${8+save.completed.length/CAMPAIGN.length*92}%`}}/><div className="route-map campaign-route"><svg className="route-line" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M 8.5 15 L 83.5 15 L 83.5 45 L 8.5 45 L 8.5 75 L 83.5 75"/></svg><span className="route-stamp">RUST COUNTY <b>→</b> COMMERCE BELT <b>→</b> METRO FRINGE <b>→</b> CIVIC WORKS <b>→</b> VERTICAL CITY <b>→</b> WATERWORKS</span>{CAMPAIGN.map((l,i)=><button key={l.id} disabled={i+1>save.unlocked} onClick={()=>setSelected(i)} className={`node r${l.classRank-1} ${selected===i?"selected":""} ${save.completed.includes(l.id)?"done":""} ${l.id===18?"dam-node":""}`} style={{left:`${4+((i>=4&&i<8)?7-i:i%4)*25}%`,top:`${10+Math.floor(i/4)*30}%`}}><span>{String(i+1).padStart(2,"0")}</span><small>{l.name}</small></button>)}</div><aside className="mission-card"><span>{d.region} // CLASS {d.classRank} // DISTRICT {String(selected+1).padStart(2,"0")}</span><h2>{d.name}</h2><b>{locked?"LOCKED ROUTE":d.objective}</b><p>{locked?"Clear the preceding district to open this route.":d.note}</p><div className="landmark">LANDMARK<br/><strong>{d.landmark}</strong></div><div className="medals">{[0,1,2].map(i=><i className={(save.medals[d.id]||0)>i?"earned":""} key={i}>★</i>)}</div><button className="primary" disabled={locked} onClick={()=>start(selected)}>{locked?"CLEAR PREVIOUS DISTRICT":"DEPLOY"}</button></aside></section>}
function Results({result,level,next,map,credits}:{result:Result;level:Level;next:()=>void;map:()=>void;credits:()=>void}){const final=result.id===18;return <section className="panel-screen results"><div className="results-card"><span>{final?"EVACUATION LINE CLEAR":"ROUTE CLEARED"}</span><h1>{level.name}</h1><div className="result-medals">{[0,1,2].map(i=><i className={result.medals>i?"earned":""} key={i}>★</i>)}</div><div className="stat-grid"><div><b>{result.score.toLocaleString()}</b><small>SCORE</small></div><div><b>{fmt(result.time)}</b><small>TIME</small></div><div><b>{result.medals}/3</b><small>MEDALS</small></div></div><div className="evolution">{final?"THE DAM IS GONE // THE VALLEY LIVES":`NEXT ROUTE // ${CAMPAIGN[Math.min(CAMPAIGN.findIndex(l=>l.id===level.id)+1,CAMPAIGN.length-1)].name.toUpperCase()}`}</div><div className="actions"><button onClick={map}>CAMPAIGN MAP</button><button className="primary" onClick={final?credits:next}>{final?"FINAL TRANSMISSION":"NEXT DISTRICT"}</button></div></div></section>}
function Replays({save,start,back}:{save:SaveData;start:(n:number)=>void;back:()=>void}){return <section className="panel-screen"><Top title="ROUTE REPLAYS" back={back}/><div className="cards">{CAMPAIGN.map((l,i)=><article className="contract" key={l.id}><span>{l.region} // CLASS {l.classRank}</span><h2>{l.name}</h2><p>{l.objective}</p><button disabled={!save.completed.includes(l.id)} onClick={()=>start(i)}>{save.completed.includes(l.id)?`REPLAY // BEST ${Math.round(save.best[l.id]||0).toLocaleString()}`:"CLEAR CAMPAIGN ROUTE FIRST"}</button></article>)}</div></section>}
function Garage({save,back}:{save:SaveData;back:()=>void}){const rank=CAMPAIGN[Math.min(save.unlocked-1,CAMPAIGN.length-1)].classRank;return <section className="panel-screen garage"><Top title="OUTLAW GARAGE" back={back}/><div className="vehicle-display"><Image src="/art/concepts/veh_iron_outlaw_orthographic.png" width={1024} height={1024} alt="Iron Outlaw vehicle design"/><div><span>ACTIVE CHASSIS // CLASS {rank}</span><h1>{REGIONS[rank-1][1]}</h1><p>Each region brings heavier armor and stronger impacts. Old structures become easier to break as the chassis grows.</p><div className="class-track">{REGIONS.map((r,i)=><div className={i<rank?"open":""} key={r[1]}><b>{i+1}</b><small>{r[1]}</small></div>)}</div></div></div></section>}
function Settings({save,persist,muted,setMuted,back}:{save:SaveData;persist:(s:SaveData)=>void;muted:boolean;setMuted:(x:boolean)=>void;back:()=>void}){const toggle=(k:keyof SaveData,v:boolean|number)=>persist({...save,[k]:v});return <section className="panel-screen settings"><Top title="SETTINGS & ACCESSIBILITY" back={back}/><div className="settings-grid"><label>CAMERA SHAKE <input type="range" min="0" max="1" step=".05" value={save.shake} onChange={e=>toggle("shake",+e.target.value)}/><span>{Math.round(save.shake*100)}%</span></label><label>REDUCED FLASH <button className={save.reducedFlash?"on":""} onClick={()=>toggle("reducedFlash",!save.reducedFlash)}>{save.reducedFlash?"ON":"OFF"}</button></label><label>AUTO-DRIVE <button className={save.autoDrive?"on":""} onClick={()=>toggle("autoDrive",!save.autoDrive)}>{save.autoDrive?"ON":"OFF"}</button></label><label>AUDIO <button className={!muted?"on":""} onClick={()=>setMuted(!muted)}>{muted?"MUTED":"ON"}</button></label></div><div className="controls"><h2>CONTROLS</h2><p><kbd>W</kbd> THROTTLE <kbd>S</kbd> BRAKE / REVERSE <kbd>A D</kbd> STEER <kbd>SPACE</kbd> HYDRAULIC JUMP <kbd>SHIFT</kbd> NITRO <kbd>ESC</kbd> EXIT DISTRICT</p><p>Gamepad and on-screen touch controls are active automatically.</p></div><button className="danger" onClick={()=>{if(confirm("Erase all campaign progress?")){localStorage.removeItem(saveKey);location.reload()}}}>ERASE SAVE</button></section>}
function Credits({completed,back}:{completed:boolean;back:()=>void}){return <section className="panel-screen credits"><div className="credits-inner"><Brand/><span>{completed?"THE LINE MADE IT ACROSS":"EVACUATION ROUTE COMMAND"}</span><h1>{completed?"NO RETURN":"THE IRON OUTLAW"}</h1><p>{completed?"The dam is gone. The valley lives. Far downstream, emergency radio catches the sound of an engine turning over.":"One machine runs ahead of the evacuation line."}</p><div className="credit-roll"><b>GAME DIRECTION</b><span>Richard + Codex</span><b>DESIGN FOUNDATION</b><span>Destruction routing, scale progression, arcade chase movement</span><b>CAMPAIGN</b><span>12 playable districts // 6 chassis classes // Mega Dam finale</span></div><button className="primary" onClick={back}>RETURN TO COMMAND</button></div></section>}
function Top({title,back}:{title:string;back:()=>void}){return <header className="top"><button onClick={back}>← COMMAND</button><h1>{title}</h1><div>IRON OUTLAW // CAMPAIGN</div></header>}
